version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt  # Install project dependencies
      - pip install pylint  # Install pylint for static code analysis

  pre_build:
    commands:
      - pylint $CODEBUILD_SRC_DIR/manage.py || true  

artifacts:
  files:
    - '**/*'  
